<?php
/**
 * @author MageRocket
 * @copyright Copyright (c) 2024 MageRocket (https://magerocket.com/)
 * @link https://magerocket.com/
 */

/** @var $block \MageRocket\GoCuotas\Block\Onepage\Success */
$order = $block->getOrder();
$payment = $order->getPayment();
$paymentAdditionalInformation = $payment->getAdditionalInformation() ?: [];
?>
<?php if ($block->isPaymentMethodGoCuotas()): ?>
    <div class="gocuotas-payment-information">
        <div id="go-logo">
            <img src="<?=$block->getLogo();?>" alt="Go Cuotas">
            <h3><?=__('Your payment was processed successfully');?></h3>
        </div>
        <div class="payment-information">
            <p></p>
            <?php if (isset($paymentAdditionalInformation['id'])): ?>
                <p><?=__('Transaction ID: <b>%1</b>', $paymentAdditionalInformation['id']);?></p>
            <?php endif;?>
            <?php if (isset($paymentAdditionalInformation['status'])): ?>
                <p><?=__('Payment Status: <b>%1</b>', ucfirst($paymentAdditionalInformation['status']));?></p>
            <?php endif;?>
            <?php if (isset($paymentAdditionalInformation['installments'])): ?>
                <p><?=__('Installments: <b>%1</b>', $paymentAdditionalInformation['installments']);?></p>
            <?php endif;?>
            <?php if (isset($paymentAdditionalInformation['card_number'])): ?>
                <p><?=__('Card Number: <b>%1</b>', $paymentAdditionalInformation['card_number']);?></p>
            <?php endif;?>
            <?php if (isset($paymentAdditionalInformation['card_name'])): ?>
                <p><?=__('Card Number: <b>%1</b>', $paymentAdditionalInformation['card_name']);?></p>
            <?php endif;?>
        </div>
    </div>
<?php endif ?>
